== Introduction

Lab books are an essential way to keep track of methods used to
generate results. In the same way
this book is built around a series of reusable examples to produce
scientific results. By reading, reproducing and exploring these
examples you will learn to use the Python programming language
and associated tools to speed up and improve the reproducibility
of your science.

Protocols are complete, step by step walkthroughs of an experiment. In this book this refers to protocols of data analysis,
taking you from raw data to processed data, or from data to results and publication-ready figures. Practise these protocols
using the demonstration data to make sure you understand how they work and how to apply it. In particular you should experiment
with changing the various parameters and seeing the effect these have on the outputs, in order to make informed decisions.
Once you are comfortable with the analysis, move on to working with your own data.
Possible differences between the demonstration and working with your own data are highlighted for clarity.