=== 1D ^1^H NMR data processing

1D ^1^H NMR is a common technique applied to metabolomic studies, being well suited
to untargeted analysis of complex biofluids. It has been successfully applied to
the classification and diagnosis of a number of diseases including [ref].

There are a number of important steps that must be applied prior 1D ^1^H NMR data
to statistical analysis, all gearded towards ensuring that the variation observed
in the data is representative of real biological variation and not a artifact of
sample handling, metabolite extraction or NMR acquisition. These steps are
described briefly below and approached in turn in the following method. It is
important to familiarise yourself with both the purpose of these steps, and
any associated caveats or limits, so that you can correctly apply them to your
own data.

== Setting up

To process raw NMR data we will be making use of of the `nmrglue` library. In
addition we will make use of features from the `numpy`, `scipy` and `matplotlib`
libraries, which you should already have installed.
To make sure you can run the following command on the terminal:

[.terminal]
----
pip install numpy scipy nmrglue matplotlib
----

Create a new Jupyter notebook using the Python 3 kernel, and in the first cell
enter and run the following. This will import all the neccessary libraries, as
well as using the `%matplotlib` magic to display output figures in the notebook.

[source,python]
----
%matplotlib inline
import matplotlib.pyplot as plt
import nmrglue as ng
import numpy as np
import scipy as sp
----

The demo data for this section is available for download from:
http://www.thepythonlabbook.com/data/1d-1h-nmr-data-processing.zip

Download and unzip the file into your data folder.

== Loading Bruker fid spectra



We can plot the spectra using `matplotlib`.

[source,python]
----
fig = plt.figure()
ax = fig.add_subplot()
ax.plot(np.range(0, data.shape[0]), data)
----

[source,python]
////
fig.savefig('./figures/1d-1h-nmr-data-processing/single-spectra-raw.tif')
////


== Fourier transform



== Batch loading + FFT for multiple spectra
